
project_id = "supabase"
[api]
enabled = true
port = 54321
[db]
port = 54322
[realtime]
enabled = true
[studio]
enabled = true
port = 54323
[inbucket]
enabled = true
port = 54324
[auth]
enabled = true
[storage]
enabled = true
[edge_functions]
[functions.generate-linkedin-post]
verify_jwt = false
[functions.linkedin-trends]
verify_jwt = false
[functions.suggest-linkedin-topics]
verify_jwt = false
