// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pywiprwhfhxnpgaxxlae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5d2lwcndoZmh4bnBnYXh4bGFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MTk5NDMsImV4cCI6MjA2MzA5NTk0M30.oHHlfQjiBqAYnXcDcaltdpQKddq5NIF9qDiWcDqCoQI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);